/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ivan_client_util_JNIUtil */

#ifndef _Included_cn_ivan_client_util_JNIUtil
#define _Included_cn_ivan_client_util_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ivan_client_util_JNIUtil
 * Method:    printPyStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_ivan_client_util_JNIUtil_printPyStr
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
